### ISSUE TITLE
Publish brand

### ISSUE THREAD

**Issue by mmacai** [openkfw/smartenergy.goecharger#6]
Publish brand to the https://github.com/home-assistant/brands.

**Comment by IngmarM** [comment]
Cant we reuse the existing go-e brand icons / logo here? https://github.com/home-assistant/brands/tree/master/custom_integrations/goecharger

**Comment by mmacai** [comment]
Don't see any issue from my point of view, but I'm also not a legal person. Even though it's an open source product right.
